#! /usr/bin/env python3
# Copyright (C) 2015 Sebastian Pipping <sebastian@pipping.org>
# Licensed under AGPL v3 or later

from directory_bootstrap.__main__ import main


if __name__ == '__main__':
    main()
