#! /usr/bin/env python2
# Copyright (C) 2015 Sebastian Pipping <sebastian@pipping.org>
# Licensed under AGPL v3 or later

from directory_bootstrap.cli import main


if __name__ == '__main__':
    main()
