#! /usr/bin/env python2
# Copyright (C) 2015 Sebastian Pipping <sebastian@pipping.org>
# Licensed under AGPL v3 or later

if __name__ == '__main__':
    try:
        from image_bootstrap.__main__ import main
    except KeyboardInterrupt:
        pass
    else:
        main()
