#! /usr/bin/env python3
# Copyright (C) 2015 Sebastian Pipping <sebastian@pipping.org>
# Licensed under AGPL v3 or later

import signal
import sys


if __name__ == '__main__':
    try:
        from image_bootstrap.__main__ import main
    except KeyboardInterrupt:
        sys.exit(128 + signal.SIGINT)
    else:
        main()
